### ISSUE TITLE
Investigate if there's a better way of handling production vs test environments

### ISSUE THREAD

**Issue by aquarat** [api3dao/wallet-watcher#9]
The wallet watcher uses an ENV flag to determine if top ups are a dry-run or actually executed.

I wonder if there's a better way of handling this? or maybe it's up to the user to use different wallets for dev and production? WDYT @vponline ?

eg. `A WALLET_ENABLE_SEND_FUNDS env must be set to any value in production to enable actual wallet top-ups.`

**Comment by vponline** [comment]
I like the current option because it allows you to deploy the app without enabling top ups and then enabling them without a re-deployment (by changing the env value in the aws console). Another option would be to have it explicitly in the config as a field.

I think other options like detecting local runs through `NODE_ENV` or a specific `stage` could be quite risky.

**Comment by aquarat** [comment]
Cool, let's leave it then. Thanks for the input :)
